import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;

/**
 * Stores a list of Person objects and a string variable 'fileName'.
 * <p>
 * list is generated by opening the file under 'fileName' 
 * and storing that data.
 * 
 * @author Ifekharul Islam
 * @version 3.0, 30/08/2022
 */
public class Contacts{
	private ArrayList<Person> contactList = new ArrayList<>();
	
	
	/**
	 * Returns a list of 'Person' objects.
	 * 
	 * @return list containing 'Person' objects.
	 */
	public ArrayList<Person> getContactList(){
		return contactList;
	}
	/**
	 * Adds to the list of objects with sent object.
	 * @param newItem new object to append to the list.
	 */
	public void addToContactList(Person newItem){
		contactList.add(newItem);
	}
	
	/**
	 * Reads from the 'poisedpms' database, queries the table contacts
	 * and uses the content to create objects of 'Person' and appends to
	 * an arrayList.
	 * 
	 * @see Person
	 */
	public void setContactList() {
		try {
			Connection connection = DriverManager.getConnection(
                    "jdbc:mysql://localhost:3306/poisedpms?useSSL=false",
                    "otheruser",
                    "swordfish"
                    );
			
			Statement statement = connection.createStatement();
			
			ResultSet results = statement.executeQuery("SELECT * from contacts");
			
			while (results.next()) {
				contactList.add(new Person(results.getString("Name"), results.getString("Telephone")
						,results.getString("Email"), results.getString("Address")));
			}
			
			connection.close();
			statement.close();
			results.close();
		}catch (SQLException e) {
            // We only want to catch a SQLException - anything else is off-limits for now.
            e.printStackTrace();
		}
	}
}
